version: '2'
services:
    tester-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/tester/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=tester
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
